BASE_DIR = ..
TARGET_DIR = $(BASE_DIR)/docs/app
TARGETS = \
		  $(TARGET_DIR)/$(BUNDLE_BASENAME).js \
		  $(TARGET_DIR)/$(VENDOR_BASENAME).js \
		  $(TARGET_DIR)/index.html
USE_REACT := 1
include $(BASE_DIR)/.makefiles/conf.makefile
